### ISSUE TITLE
Box references are not removed from rbush

### ISSUE THREAD

**Issue by GustavAT** [MazeMap/Leaflet.LayerGroup.Collision#10]
The `removeLayer()` function tries to remove the _cached relative box_ from the rbush, but the `_maybeAddLayerToBush()` function inserts the _calculated position_ (_latLngToLayerPoint()_-offset).
The items stored in the rbush differ from the cached ones and will never get removed.

Tested with Leaflet 1.0.3.

**Comment by vvavepacket** [comment]
tested the issue in 1.0.7. even if I set the rbush data to empty, the data is still persistent.

**Comment by GustavAT** [comment]
I just figured out the error: An older version of rbush.js caused the unexpected behaviour.

Everything works fine after updating to the latest version.
