### ISSUE TITLE
Combinable with Angular?

### ISSUE THREAD

**Issue by tobiasgruber-at** [MazeMap/Leaflet.LayerGroup.Collision#15]
Is it possible to use this with the 'ngx-leaflet' package for Angular? 
If so, please let me know! :)

Have a great day!

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
