### ISSUE TITLE
new releases for last commits

### ISSUE THREAD

**Issue by tmeedend** [MazeMap/Leaflet.LayerGroup.Collision#7]
Hello,

Can you please add a new release for your last commits please ?

I would like to deploy your work on http://www.webjars.org/npm so that your library can be used as a maven dependency, but webjars only scans for releases on github.

Thank you for your great work !

**Comment by IvanSanchez** [comment]
The last commit is literally a version bump made at the same time as the last `npm publish`. There's nothing else to do.

**Comment by IvanSanchez** [comment]
Wait, did you mean a github tag-based release?

**Comment by tmeedend** [comment]
I think yes. The releases that are listed here : https://github.com/MazeMap/Leaflet.LayerGroup.Collision/releases

If I go on webjars, it only lists the 0.1.0 release, which is old, and I would like to deploy on webjars the last version of your work. You can check it by clicking on « add a new NPM Webjar » on the webjars page I gave you. You put your repo URL, and then you can see the available releases.

Thank you again.

**Comment by IvanSanchez** [comment]
OK, that clears things up. I usually do `npm release` only in my packages.

**Comment by IvanSanchez** [comment]
Fixed by https://github.com/MazeMap/Leaflet.LayerGroup.Collision/releases/tag/v0.3.1

**Comment by tmeedend** [comment]
Ok thank you !
It stills read the last version as 0.1.0. I don't what webjars reads, maybe your bower.json ?
Still, I am going to try to deploy version 0.1.0 and see what code it will deploy.

EDIT : it's now listed but doesn't work. I am going to fill a bug to webjars.
